### ISSUE TITLE
Using headless =true generate timeout in searching page components with GetText and/or GetPlaceHolder

### ISSUE THREAD

**Issue by TheCyberman** [PragmaticFlow/NBomber.WebBrowser#5]
Hi,
i have created a scenario that open a browser and do different things on the same page with different steps, in order to measure each single function.
looks like that if I set headless = true the second step is always in timeout but if i run the same code with headless = false it works .

Here is the code ( I am using last version of both PlayWright and NBomber and relative plugins).

Can you take a look please? 

public async Task Run()
{

    using var playwright = await Playwright.CreateAsync();

    await using var browser = await playwright.Chromium.LaunchAsync(
        new BrowserTypeLaunchOptions
        {
            Headless = false,
            Channel = "chrome"
        }
    );

    var loginScenario = Scenario.Create("MyWebSite Login", async context =>
    {
        var page = await browser.NewPageAsync();

        var step1 = await Step.Run("Open MyWebsite", context, async () =>
        {
            var pageResponse = await page.GotoAsync("MyWebsiteUrl");

            await page.WaitForURLAsync("MyWebsiteUrl/Account/**");

            var html = await page.ContentAsync();
            var totalSize = await page.GetDataTransferSize();

            return Response.Ok(sizeBytes: totalSize);
        });

        var step2 = await Step.Run("Login MyWebsiteUrl", context, async () =>
        {
            await page.GetByPlaceholder("UserName").FillAsync("MyUser");
            await page.GetByPlaceholder("Password").FillAsync("MyPass");
            await page.GetByText("Login").ClickAsync();

            var html = await page.ContentAsync();
            var totalSize = await page.GetDataTransferSize();

            return Response.Ok(sizeBytes: totalSize);
        });

        await page.CloseAsync();

        return Response.Ok();
    })
    .WithWarmUpDuration(TimeSpan.FromSeconds(5))
    .WithLoadSimulations(   
            Simulation.RampingConstant (5, TimeSpan.FromSeconds(30)),
    )
    .WithRestartIterationOnFail(false);  //tried with and without but got same behaviour

**Comment by AntyaDev** [comment]
Hi @TheCyberman 
How can we reproduce it? What server URL should we use?

**Comment by TheCyberman** [comment]
Hi @AntyaDev I cannot share unfortunatelly the url as they are local ones but I have been able to bypass the problem and understood when the issue happens:

Bascially when I need to get the username and password text to fill and the button to submit I was going to use :

 await page.GetByPlaceholder("UserName").FillAsync("MyUser");
        await page.GetByPlaceholder("Password").FillAsync("MyPass");
        await page.GetByText("Login").ClickAsync();

This means that I was getting the first 2 compontents by a placeholder and the otherone by text.

With this code I am not able to find anything if I am in headless mode.

But going directly by locators:

 await page.Locator("//*[@id=\"username-input\"]").FillAsync("MyUser");
 await page.Locator("//*[@id=\"password-input\"]").FillAsync("MyPass!");
 await page.Locator("xpath=/html/body/main/div/div/div/div/div[2]/form/div[4]/div/button").ClickAsync();
 
 It worked.
 
 So looks like the issue is using PLaywright getbytext and getbyplaceholder rather that using directly Locator.

I do not have anymore the problem so happy if you want to close but could be interesting making a check using GetByText and GetByPlaceholder of playwright instead of locator and see why it does not work?
